"""initial migration

Revision ID: 326cd46f7b62
Revises: 
Create Date: 2025-04-24 09:40:43.082067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326cd46f7b62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
