"""third migration

Revision ID: 38a399d49f79
Revises: 7d56429e152b
Create Date: 2025-04-25 23:59:14.958253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a399d49f79'
down_revision = '7d56429e152b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('primary_care_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('insurance_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('insurance_policy_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('medical_history', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_medications', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('family_medical_history', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('family_medical_history')
        batch_op.drop_column('current_medications')
        batch_op.drop_column('medical_history')
        batch_op.drop_column('allergies')
        batch_op.drop_column('insurance_policy_number')
        batch_op.drop_column('insurance_provider')
        batch_op.drop_column('primary_care_provider')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('occupation')
        batch_op.drop_column('address')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
