"""client modal

Revision ID: 7d56429e152b
Revises: ff83aa360802
Create Date: 2025-04-24 15:49:14.511527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d56429e152b'
down_revision = 'ff83aa360802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slogan', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('program_manager', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('program_manager')
        batch_op.drop_column('slogan')

    # ### end Alembic commands ###
