"""programmes

Revision ID: 8ade7e34e7ba
Revises: 38a399d49f79
Create Date: 2025-04-27 15:08:20.364543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ade7e34e7ba'
down_revision = '38a399d49f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_audience', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('program_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('contact_email')
        batch_op.drop_column('program_type')
        batch_op.drop_column('target_audience')

    # ### end Alembic commands ###
